uploads = []
generated = []

[[outputs]]
id = "-164AX1AOQnl_sVU3lvqB"
uri = "file://artifacts/larsha-tech/src/assets/repair-hero.jpg"
type = "image"
title = "modern professional tech repair shop laptop repair motherboard soldering or fixing computer"

[[outputs]]
id = "XKHDf-FGqtaRr_5l3Tpol"
uri = "file://artifacts/larsha-tech/src/assets/web-dev.jpg"
type = "image"
title = "modern website development coding on screen with coffee in professional environment"
